export const FETCH_ALL_MOVIES_REQUEST = "FETCH_ALL_MOVIES_REQUEST";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";

export const FETCH_SINGLE_MOVIE_REQUEST = "FETCH__SINGLE_MOVIE_REQUEST";
export const FETCH_SINGLE_MOVIE_SUCCESS = "FETCH__SINGLE_MOVIE_SUCCESS";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";

export const FETCH_PAGE_OF_MOVIES_REQUEST = "FETCH_PAGE_OF_MOVIES_REQUEST";

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";

export const POST_LIKE_MOVIE_REQUEST = "POST_LIKE_MOVIE_REQUEST";
export const POST_LIKE_MOVIE_SUCCESS = "POST_LIKE_MOVIE_SUCCESS";
export const POST_LIKE_MOVIE_ERROR = "POST_LIKE_MOVIE_ERROR";

export const FETCH_POPULAR_MOVIES_REQUEST = "FETCH_POPULAR_MOIES_REQUEST";
export const FETCH_POPULAR_MOVIES_SUCCESS = "FETCH_POPULAR_MOVIES_SUCCESS";

export const FETCH_WATCH_LIST_REQUEST = "FETCH_WATCH_LIST_REQUEST";
export const FETCH_WATCH_LIST_SUCCESS = "FETCH_WATCH_LIST_SUCCESS";

export const ADD_WATCH_LIST_ITEM_REQUEST = "ADD_WATCH_LIST_ITEM_REQUEST";
export const ADD_WATCH_LIST_ITEM_SUCCESS = "ADD_WATCH_LIST_ITEM_SUCCESS";

export const UPDATE_WATCH_LIST_ITEM_REQUEST = "UPDATE_WATCH_LIST_ITEM_REQUEST";
export const UPDATE_WATCH_LIST_ITEM_SUCCESS = "UPDATE_WATCH_LIST_ITEM_SUCCESS";

export const REMOVE_WATCH_LIST_ITEM = "REMOVE_WATCH_LIST_ITEM";
export const REMOVE_WATCH_LIST_ITEM_SUCCESS = "REMOVE_WATCH_LIST_ITEM_SUCCESS";

export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR";

export const FETCH_MOVIE_OMDB_REQUEST = "FETCH_MOVIE_OMDB_REQUEST";
export const FETCH_MOVIE_OMDB_SUCCESS = "FETCH_MOVIE_OMDB_SUCCESS";

export const POST_MOVIE_IMAGE_REQUEST = "POST_MOVIE_IMAGE_REQUEST";
export const POST_MOVIE_IMAGE_SUCCESS = "POST_MOVIE_IMAGE_SUCCESS";
