export const FETCH_ALL_MOVIES_REQUEST = "FETCH_ALL_MOVIES_REQUEST";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";

export const FETCH_SINGLE_MOVIE_REQUEST = "FETCH__SINGLE_MOVIE_REQUEST";
export const FETCH_SINGLE_MOVIE_SUCCESS = "FETCH__SINGLE_MOVIE_SUCCESS";
