export const FETCH_ALL_MOVIES_REQUEST = "FETCH_ALL_MOVIES_REQUEST";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";

export const FETCH_SINGLE_MOVIE_REQUEST = "FETCH__SINGLE_MOVIE_REQUEST";
export const FETCH_SINGLE_MOVIE_SUCCESS = "FETCH__SINGLE_MOVIE_SUCCESS";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";

export const FETCH_PAGE_OF_MOVIES_REQUEST = "FETCH_PAGE_OF_MOVIES_REQUEST";

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";
