export const FETCH_MOVIE_COMMENTS_REQUEST = "FETCH_MOVIE_COMMENTS_REQUEST";
export const FETCH_MOVIE_COMMENTS_SUCCESS = "FETCH_MOVIE_COMMENTS_SUCCESS";

export const POST_MOVIE_COMMENT_REQUEST = "POST_MOVIE_COMMENT_REQUEST";
export const POST_MOVIE_COMMENT_SUCCESS = "POST_MOVIE_COMMENT_SUCCESS";
export const POST_MOVIE_COMMENT_ERROR = "POST_MOVIE_COMMENT_ERROR";

export const FETCH_MOVIE_COMMENT_PAGE_SUCCESS =
  "FETCH_MOVIE_COMMENT_PAGE_SUCCESS";
